version: "3.9"
 
services:
  learningBase:
    build: .
    image: olexuni/learningbase_arpuprediction
    volumes:
      - ai_system:/tmp
    command:
      - sh
      - "-c"
      - |
        rm -rf /tmp/learningBase/ && cp -r /learningBase/ /tmp/ ;
 
volumes:
  ai_system:
    external: true